---

- hosts: all
  become: true
  pre_tasks: #gives us order executing tasks, plays

  #play for updating centos package manager and system
  - name: update repo cache (CentOS)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  #play for updating ubuntu package manager and system
  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false #cleans the output. if change occurs we want see it in the terminal
    when: ansible_distribution == "Ubuntu"


- hosts: all
  become: true
  roles:
    - base

- hosts: localhost #workstation
  become: true
  roles:
    - workstation

- hosts: web_servers
  become: true
  roles:
    - web_servers
